MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnext101'
        PRETRAINED: True
        OUT_CHANNELS: [512, 1024, 2048, 512, 512, 512]
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: (360,270)
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 120000
    LR_STEPS: [60000, 80000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 3e-4
OUTPUT_DIR: 'outputs/resnet50_360x270_NormMirrExpCrop'
DATASET_DIR: "datasets"