MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnext101'
        PRETRAINED: True
        OUT_CHANNELS: [512, 512, 512, 512, 512, 512]
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: (360,270)
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 80000
    LR_STEPS: [24000, 34000]
    GAMMA: 0.1
    BATCH_SIZE: 32
    LR: 2e-4
OUTPUT_DIR: 'outputs/resnet34_360x270_FPNV2_photometric'
DATASET_DIR: "datasets"